// Sem VII elective baskets.
// Course codes and names generated from the official allocation sheets
// published at https://github.com/aaditagrawal/elective-cutoffs
// (data/seventh-semester.json). Section rooms for the ICT/CCE offerings come
// from the School of Computer Engineering room allocation sheet.
//
// Ordered ICT-first within each basket, then by course code.

// Type-only import: erased at compile time, so no runtime cycle with timetable-data.
import type { ElectiveOption, ElectiveType } from "@/lib/timetable-data";

export const electiveOptions: Record<ElectiveType, ElectiveOption[]> = {
  "PE-3": [
    {
      id: "ict-4403-e",
      abbreviation: "FGAI [E]",
      code: "ICT 4403",
      name: "Foundations of Generative Artificial Intelligence",
      faculty: [{ name: "TBD" }],
      room: "AB5-314",
    },
    {
      id: "ict-4403-f",
      abbreviation: "FGAI [F]",
      code: "ICT 4403",
      name: "Foundations of Generative Artificial Intelligence",
      faculty: [{ name: "TBD" }],
      room: "AB5-315",
    },
    {
      id: "ict-4413-e",
      abbreviation: "CFCL [E]",
      code: "ICT 4413",
      name: "Cyber Forensics and Cyber Laws",
      faculty: [{ name: "TBD" }],
      room: "AB5-316",
    },
    {
      id: "aae-4402",
      abbreviation: "AAE 4402",
      code: "AAE 4402",
      name: "Turbomachinery Aerodynamics",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "aae-4407",
      abbreviation: "AAE 4407",
      code: "AAE 4407",
      name: "Aerospace Embedded Systems, Software, Safety and Security",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "aae-4415",
      abbreviation: "AAE 4415",
      code: "AAE 4415",
      name: "Fatigue Failure and Analysis",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "aae-4419",
      abbreviation: "AAE 4419",
      code: "AAE 4419",
      name: "Electrical Vehicle Battery and Charging System",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "aae-4423",
      abbreviation: "AAE 4423",
      code: "AAE 4423",
      name: "Launch Vehicle Systems and Technologies",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "bio-4401",
      abbreviation: "BIO 4401",
      code: "BIO 4401",
      name: "Bioremediation",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "bio-4406",
      abbreviation: "BIO 4406",
      code: "BIO 4406",
      name: "Biopharmaceutical Engineering",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "bme-4401",
      abbreviation: "BME 4401",
      code: "BME 4401",
      name: "Introduction to Biomedical Nanotechnology",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "bme-4408",
      abbreviation: "BME 4408",
      code: "BME 4408",
      name: "Medical Imaging",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "che-4403",
      abbreviation: "CHE 4403",
      code: "CHE 4403",
      name: "Natural Gas Engineering",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "che-4405",
      abbreviation: "CHE 4405",
      code: "CHE 4405",
      name: "Industrial Waste Water Engineering (Theory & Lab)",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "che-4411",
      abbreviation: "CHE 4411",
      code: "CHE 4411",
      name: "Fuel Cell and Hydrogen Energy",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cie-4403",
      abbreviation: "CIE 4403",
      code: "CIE 4403",
      name: "Construction Materials and Quality Management",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cie-4411",
      abbreviation: "CIE 4411",
      code: "CIE 4411",
      name: "Finite Element Method of Analysis",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cie-4419",
      abbreviation: "CIE 4419",
      code: "CIE 4419",
      name: "Building Information Modelling in Construction(L&T)",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cra-4403",
      abbreviation: "CRA 4403",
      code: "CRA 4403",
      name: "Digital Media Marketing : Principles and Strategies",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cra-4407",
      abbreviation: "CRA 4407",
      code: "CRA 4407",
      name: "Machine Learning with Big Data",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cra-4411",
      abbreviation: "CRA 4411",
      code: "CRA 4411",
      name: "Data Science - Part Ii",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cra-4415",
      abbreviation: "CRA 4415",
      code: "CRA 4415",
      name: "Principles of Computing Using Data Structures",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cse-4406",
      abbreviation: "CSE 4406",
      code: "CSE 4406",
      name: "Soft Computing Paradigms",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cse-4419",
      abbreviation: "CSE 4419",
      code: "CSE 4419",
      name: "Artificial Intelligence in Cyber Security",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cse-4431",
      abbreviation: "CSE 4431",
      code: "CSE 4431",
      name: "Machine Translation",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "csf-4446",
      abbreviation: "CSF 4446",
      code: "CSF 4446",
      name: "Derivatives and Alternative Investments",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "dse-4403",
      abbreviation: "DSE 4403",
      code: "DSE 4403",
      name: "Social Network Analysis",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "dse-4407",
      abbreviation: "DSE 4407",
      code: "DSE 4407",
      name: "Enterprise Data Architecture",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ece-4408",
      abbreviation: "ECE 4408",
      code: "ECE 4408",
      name: "Analog Ic Design",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ece-4412",
      abbreviation: "ECE 4412",
      code: "ECE 4412",
      name: "Internet of Things",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ece-4422",
      abbreviation: "ECE 4422",
      code: "ECE 4422",
      name: "Edge Artificial Intelligent Computing",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ece-4443",
      abbreviation: "ECE 4443",
      code: "ECE 4443",
      name: "Bioinspired and Evolvable Systems",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ele-4410",
      abbreviation: "ELE 4410",
      code: "ELE 4410",
      name: "Soft Computing Techniques",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ele-4417",
      abbreviation: "ELE 4417",
      code: "ELE 4417",
      name: "Ev Vehicle Design & Analysis",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "hum-4403",
      abbreviation: "HUM 4403",
      code: "HUM 4403",
      name: "Financial Management",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "hum-4417",
      abbreviation: "HUM 4417",
      code: "HUM 4417",
      name: "Public Speaking",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "hum-4423",
      abbreviation: "HUM 4423",
      code: "HUM 4423",
      name: "Comparative Literature",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ice-4403",
      abbreviation: "ICE 4403",
      code: "ICE 4403",
      name: "Digital Control Systems",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mat-4057",
      abbreviation: "MAT 4057",
      code: "MAT 4057",
      name: "Reliability and Survival Analysis",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mat-4406",
      abbreviation: "MAT 4406",
      code: "MAT 4406",
      name: "Non-Linear Optimi Ation",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mie-4403",
      abbreviation: "MIE 4403",
      code: "MIE 4403",
      name: "Lubrication and Rotor Dynamics",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mie-4405",
      abbreviation: "MIE 4405",
      code: "MIE 4405",
      name: "Additive Manufacturing",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mie-4411",
      abbreviation: "MIE 4411",
      code: "MIE 4411",
      name: "Design of Heat Exchangers",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mie-4415",
      abbreviation: "MIE 4415",
      code: "MIE 4415",
      name: "Materials Characteri Ation",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mie-4422",
      abbreviation: "MIE 4422",
      code: "MIE 4422",
      name: "Elements of Mechatronics Systems",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mie-4425",
      abbreviation: "MIE 4425",
      code: "MIE 4425",
      name: "Statistical Quality Control",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mie-4440",
      abbreviation: "MIE 4440",
      code: "MIE 4440",
      name: "Machine Learning",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mte-4407",
      abbreviation: "MTE 4407",
      code: "MTE 4407",
      name: "Internetworking for Industries",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mte-4411",
      abbreviation: "MTE 4411",
      code: "MTE 4411",
      name: "Robot Path Planning and Mobile Robots",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "phy-4403",
      abbreviation: "PHY 4403",
      code: "PHY 4403",
      name: "Introduction to Astronomical Instrumentation",
      faculty: [{ name: "TBD" }],
    },
  ],
  "PE-4": [
    {
      id: "ict-4404-e",
      abbreviation: "NCA [E]",
      code: "ICT 4404",
      name: "Neural Computation and Applications",
      faculty: [{ name: "TBD" }],
      room: "AB5-313",
    },
    {
      id: "ict-4404-f",
      abbreviation: "NCA [F]",
      code: "ICT 4404",
      name: "Neural Computation and Applications",
      faculty: [{ name: "TBD" }],
      room: "AB5-314",
    },
    {
      id: "ict-4415-e",
      abbreviation: "BT [E]",
      code: "ICT 4415",
      name: "Blockchain Technology",
      faculty: [{ name: "TBD" }],
      room: "AB5-315",
    },
    {
      id: "ict-4415-f",
      abbreviation: "BT [F]",
      code: "ICT 4415",
      name: "Blockchain Technology",
      faculty: [{ name: "TBD" }],
      room: "AB5-316",
    },
    {
      id: "aae-4404",
      abbreviation: "AAE 4404",
      code: "AAE 4404",
      name: "High Speed Aerodynamics",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "aae-4408",
      abbreviation: "AAE 4408",
      code: "AAE 4408",
      name: "Aircraft Communication and Networking",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "aae-4416",
      abbreviation: "AAE 4416",
      code: "AAE 4416",
      name: "Noise, Vibrations and Harshness",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "aae-4420",
      abbreviation: "AAE 4420",
      code: "AAE 4420",
      name: "Motors and Drive Systems for Electric Vehicles",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "aae-4424",
      abbreviation: "AAE 4424",
      code: "AAE 4424",
      name: "Space Data Products and Services",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "aae-4426",
      abbreviation: "AAE 4426",
      code: "AAE 4426",
      name: "Ev Fea Analysis",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "bio-4404",
      abbreviation: "BIO 4404",
      code: "BIO 4404",
      name: "Solid Waste Management",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "bio-4408",
      abbreviation: "BIO 4408",
      code: "BIO 4408",
      name: "Molecular Modeling & Drug Design",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "bme-4403",
      abbreviation: "BME 4403",
      code: "BME 4403",
      name: "Biofabrication",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "bme-4407",
      abbreviation: "BME 4407",
      code: "BME 4407",
      name: "Decision Support System",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "che-4404",
      abbreviation: "CHE 4404",
      code: "CHE 4404",
      name: "Process Integration for Petroleum Industries",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "che-4408",
      abbreviation: "CHE 4408",
      code: "CHE 4408",
      name: "Environmental Impact Assessment and Management Plan",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "che-4412",
      abbreviation: "CHE 4412",
      code: "CHE 4412",
      name: "Bio Energy Engineering",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cie-4404",
      abbreviation: "CIE 4404",
      code: "CIE 4404",
      name: "Contract Management",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cie-4412",
      abbreviation: "CIE 4412",
      code: "CIE 4412",
      name: "Design of Foundation and Earth Retaining Structures",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cie-4420",
      abbreviation: "CIE 4420",
      code: "CIE 4420",
      name: "Sustainability Practices in Design of Building (L&T)",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cra-4404",
      abbreviation: "CRA 4404",
      code: "CRA 4404",
      name: "Marketing in Analog World",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cra-4408",
      abbreviation: "CRA 4408",
      code: "CRA 4408",
      name: "Graph Analytics for Big Data",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cra-4412",
      abbreviation: "CRA 4412",
      code: "CRA 4412",
      name: "Advanced Data Science - Part Iii",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cra-4416",
      abbreviation: "CRA 4416",
      code: "CRA 4416",
      name: "Algorithmic Thinking",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cse-4403",
      abbreviation: "CSE 4403",
      code: "CSE 4403",
      name: "Computer Vision",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cse-4420",
      abbreviation: "CSE 4420",
      code: "CSE 4420",
      name: "Database and Application Security",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cse-4432",
      abbreviation: "CSE 4432",
      code: "CSE 4432",
      name: "Deep Learning for Natural Language Processing",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "csf-4447",
      abbreviation: "CSF 4447",
      code: "CSF 4447",
      name: "Security Analysis and Portfolio Management",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "dse-4404",
      abbreviation: "DSE 4404",
      code: "DSE 4404",
      name: "Computer Vision",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "dse-4408",
      abbreviation: "DSE 4408",
      code: "DSE 4408",
      name: "Blockchain Technology",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ece-4407",
      abbreviation: "ECE 4407",
      code: "ECE 4407",
      name: "Digital Design Verification",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ece-4410",
      abbreviation: "ECE 4410",
      code: "ECE 4410",
      name: "Computer Vision",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ece-4459",
      abbreviation: "ECE 4459",
      code: "ECE 4459",
      name: "Neuromorphic Vlsi Circuits",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ele-4412",
      abbreviation: "ELE 4412",
      code: "ELE 4412",
      name: "Real Time Systems",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ele-4418",
      abbreviation: "ELE 4418",
      code: "ELE 4418",
      name: "Ev Data Analytics & Cyber Security",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "hum-4404",
      abbreviation: "HUM 4404",
      code: "HUM 4404",
      name: "Operations Management",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "hum-4410",
      abbreviation: "HUM 4410",
      code: "HUM 4410",
      name: "Financial Econometrics",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "hum-4413",
      abbreviation: "HUM 4413",
      code: "HUM 4413",
      name: "Intellectual Property Management",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "hum-4419",
      abbreviation: "HUM 4419",
      code: "HUM 4419",
      name: "Corporate Communication",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "hum-4422",
      abbreviation: "HUM 4422",
      code: "HUM 4422",
      name: "Twentieth Century Literature",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ice-4404",
      abbreviation: "ICE 4404",
      code: "ICE 4404",
      name: "System Identification",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mat-4058",
      abbreviation: "MAT 4058",
      code: "MAT 4058",
      name: "Applied Multivariate Analysis",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mat-4408",
      abbreviation: "MAT 4408",
      code: "MAT 4408",
      name: "Game Theory and Statistical Decisions",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mie-4404",
      abbreviation: "MIE 4404",
      code: "MIE 4404",
      name: "Modelling and Simulation of Dynamic Systems",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mie-4407",
      abbreviation: "MIE 4407",
      code: "MIE 4407",
      name: "Lean Manufacturing",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mie-4412",
      abbreviation: "MIE 4412",
      code: "MIE 4412",
      name: "Jet Propulsion",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mie-4416",
      abbreviation: "MIE 4416",
      code: "MIE 4416",
      name: "Fibre Reinforced Composite Mechanics & Manufacturing Techniques",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mie-4424",
      abbreviation: "MIE 4424",
      code: "MIE 4424",
      name: "Mechanical Handling Systems and Equipments",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mie-4426",
      abbreviation: "MIE 4426",
      code: "MIE 4426",
      name: "Production Planning and Control",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mie-4435",
      abbreviation: "MIE 4435",
      code: "MIE 4435",
      name: "Artificial Intelligence for Industrial Engineering.",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mte-4408",
      abbreviation: "MTE 4408",
      code: "MTE 4408",
      name: "Principles of Cryptography",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mte-4412",
      abbreviation: "MTE 4412",
      code: "MTE 4412",
      name: "Soft Robotics",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "phy-4404",
      abbreviation: "PHY 4404",
      code: "PHY 4404",
      name: "Observational Astronomy",
      faculty: [{ name: "TBD" }],
    },
  ],
  "PE-5": [
    {
      id: "ict-4442-e",
      abbreviation: "DL [E]",
      code: "ICT 4442",
      name: "Deep Learning",
      faculty: [{ name: "TBD" }],
      room: "AB5-310A",
    },
    {
      id: "ict-4442-f",
      abbreviation: "DL [F]",
      code: "ICT 4442",
      name: "Deep Learning",
      faculty: [{ name: "TBD" }],
      room: "AB5-310B",
    },
    {
      id: "ict-4442-g",
      abbreviation: "DL [G]",
      code: "ICT 4442",
      name: "Deep Learning",
      faculty: [{ name: "TBD" }],
      room: "AB5-311",
    },
    {
      id: "ict-4442-h",
      abbreviation: "DL [H]",
      code: "ICT 4442",
      name: "Deep Learning",
      faculty: [{ name: "TBD" }],
      room: "AB5-312",
    },
    {
      id: "ict-4442-i",
      abbreviation: "DL [I]",
      code: "ICT 4442",
      name: "Deep Learning",
      faculty: [{ name: "TBD" }],
      room: "AB5-313",
    },
    {
      id: "ict-4442-j",
      abbreviation: "DL [J]",
      code: "ICT 4442",
      name: "Deep Learning",
      faculty: [{ name: "TBD" }],
      room: "AB5-314",
    },
    {
      id: "ict-4451-e",
      abbreviation: "CVA [E]",
      code: "ICT 4451",
      name: "Computer Vision-Algorithms & Application",
      faculty: [{ name: "TBD" }],
      room: "AB5-315",
    },
    {
      id: "aae-4444",
      abbreviation: "AAE 4444",
      code: "AAE 4444",
      name: "Airship Technology",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "aae-4447",
      abbreviation: "AAE 4447",
      code: "AAE 4447",
      name: "Composite Materials and Structures",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "aae-4471",
      abbreviation: "AAE 4471",
      code: "AAE 4471",
      name: "Automotive Pollution and Control",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "bio-4444",
      abbreviation: "BIO 4444",
      code: "BIO 4444",
      name: "Biostatics and Design of Experiments",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "bme-4451",
      abbreviation: "BME 4451",
      code: "BME 4451",
      name: "Telemedicine",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "bme-4454",
      abbreviation: "BME 4454",
      code: "BME 4454",
      name: "Health Information System",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "che-4442",
      abbreviation: "CHE 4442",
      code: "CHE 4442",
      name: "Applied Interfacial Engineering",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "chm-4441",
      abbreviation: "CHM 4441",
      code: "CHM 4441",
      name: "Analytical Techniques and Instrumentation",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cie-4454",
      abbreviation: "CIE 4454",
      code: "CIE 4454",
      name: "Valuation of Real Properties",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cie-4456",
      abbreviation: "CIE 4456",
      code: "CIE 4456",
      name: "Bridge Engineering Design & Practices",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cse-4442",
      abbreviation: "CSE 4442",
      code: "CSE 4442",
      name: "Android Application Development",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cse-4464",
      abbreviation: "CSE 4464",
      code: "CSE 4464",
      name: "Social Network Analysis",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cse-4467",
      abbreviation: "CSE 4467",
      code: "CSE 4467",
      name: "Software Testing and Analysis",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "csf-4441",
      abbreviation: "CSF 4441",
      code: "CSF 4441",
      name: "Financial Risk Management",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "dse-4441",
      abbreviation: "DSE 4441",
      code: "DSE 4441",
      name: "Bioinformatics",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "dse-4444",
      abbreviation: "DSE 4444",
      code: "DSE 4444",
      name: "Quantum Computing",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ece-4445",
      abbreviation: "ECE 4445",
      code: "ECE 4445",
      name: "Cmos Mixed Signal Vlsi Design",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ece-4449",
      abbreviation: "ECE 4449",
      code: "ECE 4449",
      name: "Embedded Operating Systems and Rtos",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ece-4451",
      abbreviation: "ECE 4451",
      code: "ECE 4451",
      name: "Error Control Coding",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ece-4453",
      abbreviation: "ECE 4453",
      code: "ECE 4453",
      name: "Hardware for Machine Learning",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ece-4456",
      abbreviation: "ECE 4456",
      code: "ECE 4456",
      name: "Motion & Geometry Based Methods in Computer Vision",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ece-4457",
      abbreviation: "ECE 4457",
      code: "ECE 4457",
      name: "Nano Devices & Nano Sensors",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ece-4509",
      abbreviation: "ECE 4509",
      code: "ECE 4509",
      name: "Soc Design",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ele-4442",
      abbreviation: "ELE 4442",
      code: "ELE 4442",
      name: "Computer Architecture & Organization",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ele-4452",
      abbreviation: "ELE 4452",
      code: "ELE 4452",
      name: "Power System Restructuring & Market Operations",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ele-4453",
      abbreviation: "ELE 4453",
      code: "ELE 4453",
      name: "Renewable Energy",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ice-4442",
      abbreviation: "ICE 4442",
      code: "ICE 4442",
      name: "Analytical and Optical Instrumentation",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ice-4443",
      abbreviation: "ICE 4443",
      code: "ICE 4443",
      name: "Biomedical Instrumentation and Equipment",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ice-4476",
      abbreviation: "ICE 4476",
      code: "ICE 4476",
      name: "Wireless Sensor Technology",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mat-4409",
      abbreviation: "MAT 4409",
      code: "MAT 4409",
      name: "Applied Graph Theory",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mie-4442",
      abbreviation: "MIE 4442",
      code: "MIE 4442",
      name: "Applied Numerical Methods for Mechanical Engineeers",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mie-4445",
      abbreviation: "MIE 4445",
      code: "MIE 4445",
      name: "Energy Audit, Conservation and Storage",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mie-4459",
      abbreviation: "MIE 4459",
      code: "MIE 4459",
      name: "Automatic Control Systems",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mie-4462",
      abbreviation: "MIE 4462",
      code: "MIE 4462",
      name: "Business Process Re-Engineering",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mie-4482",
      abbreviation: "MIE 4482",
      code: "MIE 4482",
      name: "Automobile Engineering",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mte-4402",
      abbreviation: "MTE 4402",
      code: "MTE 4402",
      name: "Hybrid and Electric Vehicles",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mte-4442",
      abbreviation: "MTE 4442",
      code: "MTE 4442",
      name: "Augmented Reality and Virtual Reality",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mte-4462",
      abbreviation: "MTE 4462",
      code: "MTE 4462",
      name: "Micro Electro Mechanical Systems",
      faculty: [{ name: "TBD" }],
    },
  ],
  "PE-6": [
    {
      id: "ict-4447-e",
      abbreviation: "HCI [E]",
      code: "ICT 4447",
      name: "Human Computer Interaction",
      faculty: [{ name: "TBD" }],
      room: "AB5-310A",
    },
    {
      id: "ict-4447-f",
      abbreviation: "HCI [F]",
      code: "ICT 4447",
      name: "Human Computer Interaction",
      faculty: [{ name: "TBD" }],
      room: "AB5-310B",
    },
    {
      id: "ict-4447-g",
      abbreviation: "HCI [G]",
      code: "ICT 4447",
      name: "Human Computer Interaction",
      faculty: [{ name: "TBD" }],
      room: "AB5-311",
    },
    {
      id: "ict-4447-h",
      abbreviation: "HCI [H]",
      code: "ICT 4447",
      name: "Human Computer Interaction",
      faculty: [{ name: "TBD" }],
      room: "AB5-312",
    },
    {
      id: "ict-4447-i",
      abbreviation: "HCI [I]",
      code: "ICT 4447",
      name: "Human Computer Interaction",
      faculty: [{ name: "TBD" }],
      room: "AB5-313",
    },
    {
      id: "ict-4450-e",
      abbreviation: "SR [E]",
      code: "ICT 4450",
      name: "Software Reliability",
      faculty: [{ name: "TBD" }],
      room: "AB5-314",
    },
    {
      id: "ict-4450-f",
      abbreviation: "SR [F]",
      code: "ICT 4450",
      name: "Software Reliability",
      faculty: [{ name: "TBD" }],
      room: "AB5-315",
    },
    {
      id: "aae-4449",
      abbreviation: "AAE 4449",
      code: "AAE 4449",
      name: "Design of Fixed Wing Unmanned Aerial Vehicle",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "aae-4451",
      abbreviation: "AAE 4451",
      code: "AAE 4451",
      name: "Electrochemical Energy Storage Systems",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "aae-4472",
      abbreviation: "AAE 4472",
      code: "AAE 4472",
      name: "Automotive Thermal Management Systems",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "bio-4448",
      abbreviation: "BIO 4448",
      code: "BIO 4448",
      name: "Health Diagnostics",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "bme-4448",
      abbreviation: "BME 4448",
      code: "BME 4448",
      name: "Physiological Control Systems",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "bme-4452",
      abbreviation: "BME 4452",
      code: "BME 4452",
      name: "Tissue Engineering",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "che-4444",
      abbreviation: "CHE 4444",
      code: "CHE 4444",
      name: "Energy Engineering",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "che-4450",
      abbreviation: "CHE 4450",
      code: "CHE 4450",
      name: "Molecular Modelling and Simulation",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cie-4442",
      abbreviation: "CIE 4442",
      code: "CIE 4442",
      name: "Coastal Engineering",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cie-4444",
      abbreviation: "CIE 4444",
      code: "CIE 4444",
      name: "Elements of Earthquake Engineering",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cie-4458",
      abbreviation: "CIE 4458",
      code: "CIE 4458",
      name: "Geospatial Techniques in Practice",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cse-4445",
      abbreviation: "CSE 4445",
      code: "CSE 4445",
      name: "Cloud Computing",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cse-4447",
      abbreviation: "CSE 4447",
      code: "CSE 4447",
      name: "Deep Learning",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cse-4449",
      abbreviation: "CSE 4449",
      code: "CSE 4449",
      name: "Ethical Hacking and Cyber Security",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cse-4456",
      abbreviation: "CSE 4456",
      code: "CSE 4456",
      name: "Ios Application Development",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cse-4480",
      abbreviation: "CSE 4480",
      code: "CSE 4480",
      name: "Software Engineering",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "csf-4443",
      abbreviation: "CSF 4443",
      code: "CSF 4443",
      name: "Algorithmic Trading",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "dse-4442",
      abbreviation: "DSE 4442",
      code: "DSE 4442",
      name: "Biostatistics",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "dse-4446",
      abbreviation: "DSE 4446",
      code: "DSE 4446",
      name: "Soft Computing Techniques",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ece-4444",
      abbreviation: "ECE 4444",
      code: "ECE 4444",
      name: "Biomems and Micro Sensors",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ece-4447",
      abbreviation: "ECE 4447",
      code: "ECE 4447",
      name: "Data Structures and Algorithms",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ece-4460",
      abbreviation: "ECE 4460",
      code: "ECE 4460",
      name: "Number Theory and Cryptography",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ece-4463",
      abbreviation: "ECE 4463",
      code: "ECE 4463",
      name: "Pcb and System Design",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ece-4510",
      abbreviation: "ECE 4510",
      code: "ECE 4510",
      name: "Low Power Vlsi Circuit Design",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ele-4443",
      abbreviation: "ELE 4443",
      code: "ELE 4443",
      name: "Data Structures & Algorithms",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ele-4446",
      abbreviation: "ELE 4446",
      code: "ELE 4446",
      name: "Energy Auditing",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ele-4454",
      abbreviation: "ELE 4454",
      code: "ELE 4454",
      name: "Introduction to Vlsi Design",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ice-4444",
      abbreviation: "ICE 4444",
      code: "ICE 4444",
      name: "Cyber Physical Systems",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ice-4445",
      abbreviation: "ICE 4445",
      code: "ICE 4445",
      name: "Data Structures and Algorithms",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ice-4450",
      abbreviation: "ICE 4450",
      code: "ICE 4450",
      name: "Neural Network and Fuzzy Logic",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ice-4477",
      abbreviation: "ICE 4477",
      code: "ICE 4477",
      name: "Database Systems",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mat-4410",
      abbreviation: "MAT 4410",
      code: "MAT 4410",
      name: "Matrix Theory",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mie-4446",
      abbreviation: "MIE 4446",
      code: "MIE 4446",
      name: "Friction and Wear",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mie-4447",
      abbreviation: "MIE 4447",
      code: "MIE 4447",
      name: "Industrial Automation & Iot",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mie-4450",
      abbreviation: "MIE 4450",
      code: "MIE 4450",
      name: "Non-Destructive Testing of Materials",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mie-4454",
      abbreviation: "MIE 4454",
      code: "MIE 4454",
      name: "Theory of Elasticity",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mie-4472",
      abbreviation: "MIE 4472",
      code: "MIE 4472",
      name: "Management Information Systems",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mie-4486",
      abbreviation: "MIE 4486",
      code: "MIE 4486",
      name: "Natural Circulation Based Passive Heat Transport Systems",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mte-4455",
      abbreviation: "MTE 4455",
      code: "MTE 4455",
      name: "Fractional Order Modelling and Control",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mte-4459",
      abbreviation: "MTE 4459",
      code: "MTE 4459",
      name: "Machine Vision",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mte-4474",
      abbreviation: "MTE 4474",
      code: "MTE 4474",
      name: "Alternative Fuels and Green Energy Systems",
      faculty: [{ name: "TBD" }],
    },
  ],
  "PE-7": [
    {
      id: "ict-4441-e",
      abbreviation: "CC [E]",
      code: "ICT 4441",
      name: "Cloud Computing",
      faculty: [{ name: "TBD" }],
      room: "AB5-310A",
    },
    {
      id: "ict-4441-f",
      abbreviation: "CC [F]",
      code: "ICT 4441",
      name: "Cloud Computing",
      faculty: [{ name: "TBD" }],
      room: "AB5-310B",
    },
    {
      id: "ict-4441-g",
      abbreviation: "CC [G]",
      code: "ICT 4441",
      name: "Cloud Computing",
      faculty: [{ name: "TBD" }],
      room: "AB5-311",
    },
    {
      id: "ict-4444-e",
      abbreviation: "XAI [E]",
      code: "ICT 4444",
      name: "Explainable Ai",
      faculty: [{ name: "TBD" }],
      room: "AB5-312",
    },
    {
      id: "ict-4444-f",
      abbreviation: "XAI [F]",
      code: "ICT 4444",
      name: "Explainable Ai",
      faculty: [{ name: "TBD" }],
      room: "AB5-313",
    },
    {
      id: "ict-4444-g",
      abbreviation: "XAI [G]",
      code: "ICT 4444",
      name: "Explainable Ai",
      faculty: [{ name: "TBD" }],
      room: "AB5-314",
    },
    {
      id: "ict-4445-e",
      abbreviation: "GTA [E]",
      code: "ICT 4445",
      name: "Game Theory and Applications",
      faculty: [{ name: "TBD" }],
      room: "AB5-315",
    },
    {
      id: "aae-4441",
      abbreviation: "AAE 4441",
      code: "AAE 4441",
      name: "Advanced Propulsion Systems",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "aae-4482",
      abbreviation: "AAE 4482",
      code: "AAE 4482",
      name: "Automotive Product Design and Development",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "bio-4447",
      abbreviation: "BIO 4447",
      code: "BIO 4447",
      name: "Genomics and Proteomics",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "bme-4446",
      abbreviation: "BME 4446",
      code: "BME 4446",
      name: "Health Care Management",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "che-4445",
      abbreviation: "CHE 4445",
      code: "CHE 4445",
      name: "Green Processes",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "che-4446",
      abbreviation: "CHE 4446",
      code: "CHE 4446",
      name: "Industrial Safety and Risk Management",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "che-4451",
      abbreviation: "CHE 4451",
      code: "CHE 4451",
      name: "Non Newtonian Fluid Flow in Process Industries",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cie-4446",
      abbreviation: "CIE 4446",
      code: "CIE 4446",
      name: "Environmental Impact Assessment and Auditing",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cie-4451",
      abbreviation: "CIE 4451",
      code: "CIE 4451",
      name: "Non-Destructive Testing of Concrete Structures",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cie-4457",
      abbreviation: "CIE 4457",
      code: "CIE 4457",
      name: "Project Management for Professionals",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cse-4444",
      abbreviation: "CSE 4444",
      code: "CSE 4444",
      name: "Blockchain Technology",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cse-4453",
      abbreviation: "CSE 4453",
      code: "CSE 4453",
      name: "Human Computer Interface",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cse-4473",
      abbreviation: "CSE 4473",
      code: "CSE 4473",
      name: "Computer Networks",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cse-4478",
      abbreviation: "CSE 4478",
      code: "CSE 4478",
      name: "Reinforcement Learning",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "csf-4404",
      abbreviation: "CSF 4404",
      code: "CSF 4404",
      name: "Compliance and Regulation for Fintech",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "dse-4443",
      abbreviation: "DSE 4443",
      code: "DSE 4443",
      name: "Data Forensics",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "dse-4447",
      abbreviation: "DSE 4447",
      code: "DSE 4447",
      name: "Software Engineering",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ece-4441",
      abbreviation: "ECE 4441",
      code: "ECE 4441",
      name: "5G: Fundamentals and Architectures",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ece-4455",
      abbreviation: "ECE 4455",
      code: "ECE 4455",
      name: "Modern Computer Architecture and Organization",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ece-4461",
      abbreviation: "ECE 4461",
      code: "ECE 4461",
      name: "Object Oriented Programming Using C++",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ece-4469",
      abbreviation: "ECE 4469",
      code: "ECE 4469",
      name: "Switching Theory for Logic Synthesis",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ece-4471",
      abbreviation: "ECE 4471",
      code: "ECE 4471",
      name: "Vlsi Process Technology",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ece-4498",
      abbreviation: "ECE 4498",
      code: "ECE 4498",
      name: "Real Time Operating Systems",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ele-4445",
      abbreviation: "ELE 4445",
      code: "ELE 4445",
      name: "Energy Analytics",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ele-4449",
      abbreviation: "ELE 4449",
      code: "ELE 4449",
      name: "Introduction to Data Science",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ice-4453",
      abbreviation: "ICE 4453",
      code: "ICE 4453",
      name: "Reliability and Safety Engineering",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ice-4478",
      abbreviation: "ICE 4478",
      code: "ICE 4478",
      name: "Operating Systems",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mat-4412",
      abbreviation: "MAT 4412",
      code: "MAT 4412",
      name: "Algebraic Coding Theory",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mie-4444",
      abbreviation: "MIE 4444",
      code: "MIE 4444",
      name: "Biomechanics",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mie-4449",
      abbreviation: "MIE 4449",
      code: "MIE 4449",
      name: "Mems and Nano Technology",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mie-4455",
      abbreviation: "MIE 4455",
      code: "MIE 4455",
      name: "Wind Energy Technology",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mie-4458",
      abbreviation: "MIE 4458",
      code: "MIE 4458",
      name: "Steam Engineering",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mie-4480",
      abbreviation: "MIE 4480",
      code: "MIE 4480",
      name: "Waste Management",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mie-4483",
      abbreviation: "MIE 4483",
      code: "MIE 4483",
      name: "Supply Chain Management",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mte-4457",
      abbreviation: "MTE 4457",
      code: "MTE 4457",
      name: "Machine Learning",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mte-4466",
      abbreviation: "MTE 4466",
      code: "MTE 4466",
      name: "Production and Operations Management",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mte-4473",
      abbreviation: "MTE 4473",
      code: "MTE 4473",
      name: "Digital Twin for Mechatronics",
      faculty: [{ name: "TBD" }],
    },
  ],
  "OE": [
    {
      id: "aae-4312",
      abbreviation: "AAE 4312",
      code: "AAE 4312",
      name: "Introduction to Avionics and Navigation System",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "aae-4314",
      abbreviation: "AAE 4314",
      code: "AAE 4314",
      name: "Alternatives Fuels for Sustainable Environment",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "bio-4312",
      abbreviation: "BIO 4312",
      code: "BIO 4312",
      name: "Body, Mind, and Medicine",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "bio-4313",
      abbreviation: "BIO 4313",
      code: "BIO 4313",
      name: "Bioinspired Design for Engineers",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "bme-4316",
      abbreviation: "BME 4316",
      code: "BME 4316",
      name: "Nanomedicine",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "che-4314",
      abbreviation: "CHE 4314",
      code: "CHE 4314",
      name: "Introduction to Petroleum Engineering",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "chm-4311",
      abbreviation: "CHM 4311",
      code: "CHM 4311",
      name: "Analytical Methods and Instrumentation",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "chm-4313",
      abbreviation: "CHM 4313",
      code: "CHM 4313",
      name: "Fundamentals of Industrial Catalytic Processes",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cie-4311",
      abbreviation: "CIE 4311",
      code: "CIE 4311",
      name: "Air and Noise Pollution",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cie-4312",
      abbreviation: "CIE 4312",
      code: "CIE 4312",
      name: "Contract Management for Engineers",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "cie-4315",
      abbreviation: "CIE 4315",
      code: "CIE 4315",
      name: "Introduction to Remote Sensing and Gis",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ece-4312",
      abbreviation: "ECE 4312",
      code: "ECE 4312",
      name: "Electronic Product Design & Packaging",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ece-4318",
      abbreviation: "ECE 4318",
      code: "ECE 4318",
      name: "Computational Intelligence and Environmental Sustainability",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ece-4319",
      abbreviation: "ECE 4319",
      code: "ECE 4319",
      name: "Applications of Signal Processing",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ece-4320",
      abbreviation: "ECE 4320",
      code: "ECE 4320",
      name: "Introduction to Biosensors",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ece-4322",
      abbreviation: "ECE 4322",
      code: "ECE 4322",
      name: "Music & Neuroengineering",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ele-4312",
      abbreviation: "ELE 4312",
      code: "ELE 4312",
      name: "Essentials of Energy Auditing",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ele-4314",
      abbreviation: "ELE 4314",
      code: "ELE 4314",
      name: "Introduction to Renewable Energy",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ele-4315",
      abbreviation: "ELE 4315",
      code: "ELE 4315",
      name: "Introduction to Lighting Design",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "hum-4320",
      abbreviation: "HUM 4320",
      code: "HUM 4320",
      name: "Research Methods in Management",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "hum-4323",
      abbreviation: "HUM 4323",
      code: "HUM 4323",
      name: "German for Beginners",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "hum-4336",
      abbreviation: "HUM 4336",
      code: "HUM 4336",
      name: "Graphic Novels : History, Form and Culture",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "ice-4317",
      abbreviation: "ICE 4317",
      code: "ICE 4317",
      name: "Farm Automation",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "iie-4311",
      abbreviation: "IIE 4311",
      code: "IIE 4311",
      name: "Life Style Modification and Complementary and Alternative Therapies",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "iie-4318",
      abbreviation: "IIE 4318",
      code: "IIE 4318",
      name: "Media Production Techniques",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "iie-4324",
      abbreviation: "IIE 4324",
      code: "IIE 4324",
      name: "Yoga",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "iie-4335",
      abbreviation: "IIE 4335",
      code: "IIE 4335",
      name: "Introduction to Foreign Language - French I",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "iie-4340",
      abbreviation: "IIE 4340",
      code: "IIE 4340",
      name: "Yakshagana for Beginners",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "iie-4341",
      abbreviation: "IIE 4341",
      code: "IIE 4341",
      name: "Communicative Kannada",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mat-5304",
      abbreviation: "MAT 5304",
      code: "MAT 5304",
      name: "Mathematical Modelling",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mie-4314",
      abbreviation: "MIE 4314",
      code: "MIE 4314",
      name: "Energy Engineering",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "mte-4314",
      abbreviation: "MTE 4314",
      code: "MTE 4314",
      name: "Industrial Iot",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "phy-4314",
      abbreviation: "PHY 4314",
      code: "PHY 4314",
      name: "Introduction to Quantum Mechanics",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "phy-4319",
      abbreviation: "PHY 4319",
      code: "PHY 4319",
      name: "Introduction to Quantum Computing",
      faculty: [{ name: "TBD" }],
    },
    {
      id: "phy-4320",
      abbreviation: "PHY 4320",
      code: "PHY 4320",
      name: "Solar Photovoltaics and Battery Technology",
      faculty: [{ name: "TBD" }],
    },
  ],
};
